---
- name: Converge
  hosts: all
  become: true

  vars:
    github_users_absent:
      - johndoe
      - janedoe

  pre_tasks:
    - name: Update apt cache.
      ansible.builtin.apt: update_cache=true cache_valid_time=600
      register: apt_cache_update
      when: ansible_os_family == 'Debian'

    - name: Set up github_users for Debian.
      ansible.builtin.set_fact:
        github_users:
          - name: shaneholloman
            groups: sudo
          - fabpot
      when: ansible_os_family == 'Debian'

    - name: Set up github_users for RedHat.
      ansible.builtin.set_fact:
        github_users:
          - name: shaneholloman
            groups: wheel
          - fabpot
      when: ansible_os_family == 'RedHat'

    - name: Add users to be removed on first run.
      ansible.builtin.user:
        name: "{{ item }}"
        ansible.builtin.shell: /bin/bash
        createhome: false
      with_items: "{{ github_users_absent }}"
      when: apt_cache_update.changed
      tags: ['skip_ansible_lint']

  roles:
    - role: shaneholloman.github
